name: First Workflow

on: push

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "First Github Actions Job"
                ls -ltra
                cat README.md
            
            - name: Generate ASCII artwork
              run: cowsay -f dragon "Dragon" >> dragon.txt

            # - name: List files
            #   run: ls

            # - name: Read file
            #   run: cat README.md
