name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: List repository files
              run: ls -ltra

            - name: Execute shell script
              run: ./ascii-script.sh
